apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "octopus-chart.name" . }}
  labels:
    {{- include "octopus-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "octopus-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "octopus-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "octopus-chart.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name | default "custom" }}
              containerPort: {{ default .Values.service.port .Values.service.targetPort }}
              protocol: {{ .Values.service.protocol | default "TCP" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          