---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: octopus
  namespace: flux-demo
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: octopus
  chart:
    git: git@github.com:RonaldCrb/helm-operator-get-started
    path: charts/octopus-chart
    ref: master
  values:
    image:
      repository: ronaldcrb/octopus
      tag: dev
