---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: shark
  namespace: flux-demo
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: shark
  chart:
    git: git@github.com:RonaldCrb/helm-operator-get-started
    path: charts/shark-chart
    ref: master