---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: octopus-prod
  namespace: demo-prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: octopus-prod
  chart:
    git: git@github.com:RonaldCrb/helm-operator-get-started
    path: charts/octopus-chart
    ref: master
#    values:
#      image:
#        repository: stefanprodan/octopus
#        tag: 0.4.11
#      replicaCount: 3
